Changed pre-generated block logs into service

diff --git a/.gitlab-ci.yaml b/.gitlab-ci.yaml
--- a/.gitlab-ci.yaml
+++ b/.gitlab-ci.yaml
@@ -420,6 +420,10 @@ plugin_test:
       LOG_FILE: $CI_JOB_NAME.log
     command: ["--replay-blockchain", "--stop-at-block=5000000"]
 
+.test-block-log-service: &test-block-log-service
+  - name: $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE
+    alias: test-block-log-server
+
 .python_based:
   image: "$CI_REGISTRY_IMAGE/ci-base-image$TEST_IMAGE_TAG"
   extends:
@@ -668,13 +672,25 @@ test_tools_tests:
   extends: .test_tools_based
   needs:
     - !reference [.test_tools_based, needs]
-    - job: copy_testing_block_logs_to_cache
+    - job: generate_testing_block_logs_and_save_image
   variables:
+    NODE_ADDRESS: "test-block-log-server:80"
     PYTEST_TIMEOUT_MINUTES: 30
     PYTEST_JUNIT_REPORT: $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests/report.xml
     TESTING_BLOCK_LOGS_DESTINATION: $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests/testing_block_logs
+  services:
+    - *test-block-log-service
   script:
-    - cp -r $TESTING_BLOCK_LOGS_CACHE_DIR/* $TESTING_BLOCK_LOGS_DESTINATION
+    - test -n "$TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE"
+    - curl -I ${NODE_ADDRESS} || (echo "error connecting to service test-block-log-server" && false)
+    - mkdir -p $TESTING_BLOCK_LOGS_DESTINATION/empty_30
+    - wget test-block-log-server:80/testing_block_logs/empty_30/block_log --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_30/block_log
+    - wget test-block-log-server:80/testing_block_logs/empty_30/block_log.artifacts --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_30/block_log.artifacts
+    - mkdir -p $TESTING_BLOCK_LOGS_DESTINATION/empty_430
+    - wget test-block-log-server:80/testing_block_logs/empty_430/block_log_part.0001 --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_430/block_log_part.0001
+    - wget test-block-log-server:80/testing_block_logs/empty_430/block_log_part.0001.artifacts --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_430/block_log_part.0001.artifacts
+    - wget test-block-log-server:80/testing_block_logs/empty_430/block_log_part.0002 --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_430/block_log_part.0002
+    - wget test-block-log-server:80/testing_block_logs/empty_430/block_log_part.0002.artifacts --output-document=$TESTING_BLOCK_LOGS_DESTINATION/empty_430/block_log_part.0002.artifacts
     - cd $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests
     - pip install local-tools/
     - !reference [.run-pytest, script]
@@ -1205,43 +1221,6 @@ generate_testing_block_logs_and_save_image:
   tags:
   - public-runner-docker
   - hived-for-tests
-
-copy_testing_block_logs_to_cache:
-  stage: build
-  extends: .docker_image_builder_job
-  needs:
-    - job: generate_testing_block_logs_and_save_image
-      artifacts: true
-  variables:
-    TESTING_BLOCK_LOGS_CACHE_DIR: "/cache/testing_block_logs_${TESTING_BLOCK_LOG_LATEST_COMMIT_SHORT_SHA}"
-  script:
-    - echo $TESTING_BLOCK_LOGS_CACHE_DIR
-    - echo "TESTING_BLOCK_LOGS_CACHE_DIR=$TESTING_BLOCK_LOGS_CACHE_DIR" > $CI_PROJECT_DIR/testing_block_log_cache_dir.env
-    - |
-      if [ -d "$TESTING_BLOCK_LOGS_CACHE_DIR" ]; then
-        echo "Directory $TESTING_BLOCK_LOGS_CACHE_DIR exists. Skipping copy from image process..."
-      else
-        echo "Start copy testing block logs from image - $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE"
-        mkdir -p $TESTING_BLOCK_LOGS_CACHE_DIR && cd $TESTING_BLOCK_LOGS_CACHE_DIR
-        echo "Start copy block_logs from - $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE"
-        docker pull $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE
-        $CI_PROJECT_DIR/scripts/ci-helpers/export-data-from-docker-image.sh $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE $TESTING_BLOCK_LOGS_CACHE_DIR --image-path=/
-        checksum_from_image=$(docker inspect --format='{{ index .Config.Labels "testing_block_logs_checksum" }}' $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE)
-        echo "Checksum from image: $checksum_from_image"
-        checksum_after_copy=$(find $TESTING_BLOCK_LOGS_CACHE_DIR -type f | sort | xargs cat | md5sum |cut -d ' ' -f 1)
-        echo "Checksum after copy: $checksum_after_copy"
-        if [[ "$checksum_from_image" != "$checksum_after_copy" ]]; then
-          echo "Checksum mismatch detected! The checksum from the container does not match the checksum after copying."
-          exit 1
-        fi
-      fi
-    - tree $TESTING_BLOCK_LOGS_CACHE_DIR
-  artifacts:
-    reports:
-      dotenv:
-        - testing_block_log_cache_dir.env
-  tags:
-    - data-cache-storage
 
 generate_universal_block_logs_and_save_image:
   stage: build
