Improved CI block log services with templates

diff --git a/.gitlab-ci.yaml b/.gitlab-ci.yaml
--- a/.gitlab-ci.yaml
+++ b/.gitlab-ci.yaml
@@ -394,13 +394,19 @@ plugin_test:
       LOG_FILE: $CI_JOB_NAME.log
     command: ["--replay-blockchain", "--stop-at-block=5000000"]
 
-.test-block-log-service: &test-block-log-service
-  - name: $TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE
-    alias: test-block-log-server
+.test-block-log-service:
+  variables:
+    TEST_BLOCK_LOG_SERVER: "http://test-block-log-server:80"
+  services:
+    - name: $TEST_BLOCK_LOG_LATEST_VERSION_IMAGE
+      alias: test-block-log-server
 
-.universal-block-log-service: &universal-block-log-service
-  - name: $UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE
-    alias: universal-block-log-server
+.universal-block-log-service:
+  variables:
+    UNIVERSAL_BLOCK_LOG_SERVER: "http://universal-block-log-server:80"
+  services:
+    - name: $UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE
+      alias: universal-block-log-server
 
 .python_based:
   image: "$CI_REGISTRY_IMAGE/ci-base-image$TEST_IMAGE_TAG"
@@ -644,23 +650,42 @@ broadcast_tests:
   tags:
     - public-runner-docker
 
+.fetch_test_block_logs:
+  # Usage:
+  # 1. Add - !reference [.fetch_test_block_logs, script] at the beginning of your test script section.
+  # 2. Set the appropriate values for:
+  #    - TEST_BLOCK_LOG_LATEST_VERSION_IMAGE (required, should be set in testing_block_log_image_generator.sh)
+  #    - TEST_BLOCK_LOG_SERVER (required, should be set in .test-block-log-service)
+  #    - TEST_BLOCK_LOGS_SOURCES (required, should be set in test job)
+  #    - TESTING_BLOCK_LOGS_DESTINATION (required, should be set in test job)
+  script:
+    - |
+      test -n "$TEST_BLOCK_LOG_LATEST_VERSION_IMAGE"
+      test -n "$TEST_BLOCK_LOG_SERVER"
+      test -n "$TESTING_BLOCK_LOGS_DESTINATION"
+      curl -I $TEST_BLOCK_LOG_SERVER || (echo "error connecting to service test-block-log-server" && false)
+      IFS=" " read -ra BLOCK_LOGS <<< $TEST_BLOCK_LOGS_SOURCES
+      for i in "${BLOCK_LOGS[@]}"
+      do
+        echo "$i"
+        wget -q -nH -np -P $TESTING_BLOCK_LOGS_DESTINATION -r -R "index.html*" --cut-dirs=1 $TEST_BLOCK_LOG_SERVER/$i
+      done
+
 test_tools_tests:
   stage: test
-  extends: .test_tools_based
+  extends:
+    - .test_tools_based
+    - .test-block-log-service
   needs:
     - !reference [.test_tools_based, needs]
     - job: generate_testing_block_logs_and_save_image
   variables:
-    NODE_ADDRESS: "test-block-log-server:80"
     PYTEST_TIMEOUT_MINUTES: 30
     PYTEST_JUNIT_REPORT: $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests/report.xml
+    TEST_BLOCK_LOGS_SOURCES: testing_block_logs/empty_30/ testing_block_logs/empty_430/
     TESTING_BLOCK_LOGS_DESTINATION: $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests
-  services:
-    - *test-block-log-service
   script:
-    - test -n "$TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE"
-    - curl -I ${NODE_ADDRESS} || (echo "error connecting to service test-block-log-server" && false)
-    - wget -nH -np -P $TESTING_BLOCK_LOGS_DESTINATION -r -R "index.html*" --cut-dirs=1 test-block-log-server:80/testing_block_logs/
+    - !reference [.fetch_test_block_logs, script]
     - cd $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests
     - pip install local-tools/
     - !reference [.run-pytest, script]
@@ -906,7 +931,9 @@ message_format_live_mainnet_tests:
 
 foundation_layer_tests:
   stage: test
-  extends: .test_tools_based
+  extends:
+  - .test_tools_based
+  - .test-block-log-service
   needs:
     - !reference [.test_tools_based, needs]
     - job: generate_testing_block_logs_and_save_image
@@ -915,8 +942,6 @@ foundation_layer_tests:
     PYTEST_JUNIT_REPORT: $CI_PROJECT_DIR/tests/python/functional/foundation_layer_tests/report.xml
     NODE_ADDRESS: "test-block-log-server:80"
     TESTING_BLOCK_LOGS_DESTINATION: $CI_PROJECT_DIR/tests/python/hive-local-tools/test-tools/tests
-  services:
-    - *test-block-log-service
   script:
     - test -n "$TESTING_BLOCK_LOG_LATEST_VERSION_IMAGE"
     - curl -I ${NODE_ADDRESS} || (echo "error connecting to service test-block-log-server" && false)
@@ -1221,24 +1246,43 @@ generate_universal_block_logs_and_save_image:
   - public-runner-docker
   - hived-for-tests
 
+.fetch_universal_block_logs:
+  # Usage:
+  # 1. Add - !reference [.fetch_universal_block_logs, script] at the beginning of your test script section.
+  # 2. Set the appropriate values for:
+  #    - UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE (required, should be set in universal_block_log_image_generator.sh)
+  #    - UNIVERSAL_BLOCK_LOG_SERVER (required, should be set in .universal-block-log-service)
+  #    - UNIVERSAL_BLOCK_LOGS_SOURCES (required, should be set in test job)
+  #    - UNIVERSAL_BLOCK_LOGS_DESTINATION (required, should be set in test job)
+  script:
+    - |
+      test -n "$UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE"
+      test -n "$UNIVERSAL_BLOCK_LOG_SERVER"
+      test -n "$UNIVERSAL_BLOCK_LOGS_DESTINATION"
+      curl -I $UNIVERSAL_BLOCK_LOG_SERVER || (echo "error connecting to service universal-block-log-server" && false)
+      IFS=" " read -ra BLOCK_LOGS <<< $UNIVERSAL_BLOCK_LOGS_SOURCES
+      for i in "${BLOCK_LOGS[@]}"
+      do
+        echo "$i"
+        wget -q -nH -np -P $UNIVERSAL_BLOCK_LOGS_DESTINATION -r -R "index.html*" --cut-dirs=1 $UNIVERSAL_BLOCK_LOG_SERVER/$i
+      done
+
 universal_block_log_tests:
   stage: test
-  extends: .test_tools_based
+  extends:
+    - .test_tools_based
+    - .universal-block-log-service
   needs:
     - !reference [.test_tools_based, needs]
     - job: generate_universal_block_logs_and_save_image
       artifacts: true
   variables:
-    NODE_ADDRESS: "universal-block-log-server:80"
     PYTEST_TIMEOUT_MINUTES: 8
     PYTEST_JUNIT_REPORT: $CI_PROJECT_DIR/tests/python/functional/util/universal_block_logs/report.xml
+    UNIVERSAL_BLOCK_LOGS_SOURCES: universal_block_logs/
     UNIVERSAL_BLOCK_LOGS_DESTINATION: $CI_PROJECT_DIR/tests/python/functional/util/universal_block_logs
-  services:
-    - *universal-block-log-service
   script:
-    - test -n "$UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE"
-    - curl -I ${NODE_ADDRESS} || (echo "error connecting to service universal-block-log-server" && false)
-    - wget -nH -np -P $UNIVERSAL_BLOCK_LOGS_DESTINATION -r -R "index.html*" --cut-dirs=1 universal-block-log-server:80/universal_block_logs/
+    - !reference [.fetch_universal_block_logs, script]
     - cd $CI_PROJECT_DIR/tests/python/functional/util/universal_block_logs
     - !reference [.run-pytest, script]
   tags:
@@ -1246,21 +1290,19 @@ universal_block_log_tests:
 
 colony_tests:
   stage: test
-  extends: .test_tools_based
+  extends:
+    - .test_tools_based
+    - .universal-block-log-service
   needs:
     - !reference [.test_tools_based, needs]
     - job: generate_universal_block_logs_and_save_image
   variables:
-    NODE_ADDRESS: "universal-block-log-server:80"
     PYTEST_TIMEOUT_MINUTES: 10
     PYTEST_JUNIT_REPORT: $CI_PROJECT_DIR/tests/python/functional/colony/report.xml
+    UNIVERSAL_BLOCK_LOGS_SOURCES: universal_block_logs/block_log_single_sign/
     UNIVERSAL_BLOCK_LOGS_DESTINATION: $CI_PROJECT_DIR/tests/python/functional/util/universal_block_logs
-  services:
-    - *universal-block-log-service
   script:
-    - test -n "$UNIVERSAL_BLOCK_LOG_LATEST_VERSION_IMAGE"
-    - curl -I ${NODE_ADDRESS} || (echo "error connecting to service universal-block-log-server" && false)
-    - wget -nH -np -P $UNIVERSAL_BLOCK_LOGS_DESTINATION -r -R "index.html*" --cut-dirs=1 universal-block-log-server:80/universal_block_logs/
+    - !reference [.fetch_universal_block_logs, script]
     - cd $CI_PROJECT_DIR/tests/python/functional/colony
     - !reference [.run-pytest, script]
   tags:
